In [60]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print("Libraries import successfully")

Libraries import successfully


In [7]:
a = np.array([1, 2, 3, 4, 5])

In [8]:
type(a)

numpy.ndarray

In [9]:
#finding the size of the array
a.size

5

In [10]:
# finding the shape
a.shape

(5,)

In [11]:
a = np.array([1, 2, 3, 4, 5, 6])

In [12]:
a2 = a[np.newaxis, :]
a2

array([[1, 2, 3, 4, 5, 6]])

In [13]:
a2.shape

(1, 6)

In [17]:
vec = np.array([1, 2, 3])

In [18]:
vec[0]

1

In [19]:
vec[1]

2

In [46]:
# creating a 2D array
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [10, 11, 12, 13]])

In [21]:
a.size

12

In [22]:
a.shape

(3, 4)

In [23]:
a.ndim

2

In [24]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [25]:
a[a<5]

array([1, 2, 3, 4])

In [26]:
a[a>=5]

array([ 5,  6,  7,  8, 10, 11, 12, 13])

In [34]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [35]:
print(a[a%2])

[[[5 6 7 8]
  [1 2 3 4]
  [5 6 7 8]
  [1 2 3 4]]

 [[5 6 7 8]
  [1 2 3 4]
  [5 6 7 8]
  [1 2 3 4]]

 [[1 2 3 4]
  [5 6 7 8]
  [1 2 3 4]
  [5 6 7 8]]]


In [44]:
ones = np.ones((3, 4), dtype=int)

In [45]:
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [41]:
zeros = np.zeros(10, dtype=int)

In [42]:
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [47]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [48]:
newarray = a + ones
newarray

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [49]:
newarray.min()

2

In [50]:
newarray.max()

14

In [51]:
newarray.sum()

94

In [52]:
newarray

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [53]:
# reshaping arrays
arr2 =newarray.reshape(4, 3)

In [54]:
arr2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 11],
       [12, 13, 14]])

In [55]:
arr2.flatten()

array([ 2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14])

In [57]:
titanic = pd.read_csv("titanic.csv")

In [58]:
titanic

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                       Myles, Mr. Thomas Francis    male  62.0      0      0   
3                                Wirz, Mr. Albert    male  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
..                                            ...     ...   ...    ...    ...   
413                            Spector, Mr. Woolf    male   NaN      0      0   
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0   
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0   
416                           Ware, Mr. Frederick    male   NaN      0      0   
417                      Peter, Master. Michael J    male   NaN      1      1   

                 Ticket      Fare Cabin Embarked  
0                330911    7.8292   NaN        Q  
1                363272    7.0000   NaN        S  
2                240276    9.6875   NaN        Q  
3                315154    8.6625   NaN        S  
4               3101298   12.2875   NaN        S  
..                  ...       ...   ...      ...  
413           A.5. 3236    8.0500   NaN        S  
414            PC 17758  108.9000  C105        C  
415  SOTON/O.Q. 3101262    7.2500   NaN        S  
416              359309    8.0500   NaN        S  
417                2668   22.3583   NaN        C  

[418 rows x 12 columns]

In [59]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Survived     418 non-null    int64  
 2   Pclass       418 non-null    int64  
 3   Name         418 non-null    object 
 4   Sex          418 non-null    object 
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64  
 7   Parch        418 non-null    int64  
 8   Ticket       418 non-null    object 
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object 
 11  Embarked     418 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB
